import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { FloatingActionButton } from "@/components/fab";
import { CookieConsentBanner } from "@/components/cookie-consent";
import { SupportBot } from "@/components/support-bot";
import { SITE_URL, SITE_NAME, absoluteUrl, jsonLdProps } from "@/lib/site";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#0b0f15" },
    { media: "(prefers-color-scheme: light)", color: "#f5f7fa" },
  ],
};

// OG/Twitter images are generated by src/app/opengraph-image.tsx (Next file convention).
const OG_IMAGE = absoluteUrl("/opengraph-image");

export const metadata: Metadata = {
  title: {
    default: "FilesWow.com — Free PDF, Word & Image Tools Online",
    template: "%s | FilesWow.com",
  },
  description:
    "100+ free PDF, Word, and image tools. Merge, split, compress, convert, edit, and transform documents — entirely in your browser. No upload required. 100% private.",
  keywords: [
    "free PDF tools",
    "online PDF editor",
    "merge PDF free",
    "split PDF online",
    "compress PDF",
    "PDF to Word",
    "Word to PDF",
    "free online PDF converter",
    "no upload PDF tools",
    "client-side PDF editor",
    "private PDF tools no server",
    "free Word document converter",
    "online image editor free",
    "convert JPG to PDF online",
    "PDF watermark free online",
    "OCR PDF free browser",
    "remove background image free",
    "FilesWow",
    "FilesWow.com",
    "fileswow free tools",
    "free document tools online",
    "PDF tools no registration",
    "Word to HTML converter",
    "image compress online free",
    "batch file converter free",
  ],
  authors: [{ name: "FilesWow.com" }],
  creator: "FilesWow.com",
  publisher: "FilesWow.com",
  metadataBase: new URL(SITE_URL),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "FilesWow.com — Free PDF, Word & Image Tools Online",
    description:
      "100+ free PDF, Word, and image tools. Your files never leave your device. No upload. No account. No tracking.",
    type: "website",
    siteName: SITE_NAME,
    url: "/",
    images: [
      {
        url: OG_IMAGE,
        width: 1200,
        height: 630,
        alt: "FilesWow.com — Free PDF & Word Tools Online",
        type: "image/png",
      },
    ],
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "FilesWow.com — Free PDF, Word & Image Tools Online",
    description:
      "100+ free PDF, Word, and image tools. No upload required. 100% private.",
    images: [OG_IMAGE],
    creator: "@fileswow",
    site: "@fileswow",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: "/favicon.svg",
    // apple-touch-icon is generated by src/app/apple-icon.tsx (Next file convention).
    apple: "/apple-icon",
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  const organizationJsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: SITE_NAME,
    url: "/",
    logo: "/icon",
    sameAs: [
      "https://www.producthunt.com/products/fileswow-com",
      "https://www.producthunt.com/posts/fileswow-com",
    ],
    contactPoint: {
      "@type": "ContactPoint",
      contactType: "customer support",
      availableLanguage: "English",
    },
  };

  const websiteJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: SITE_NAME,
    url: "/",
    description: "100+ free PDF, Word, and image tools. Processed entirely in your browser.",
  };

  const softwareJsonLd = {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "FilesWow.com",
    applicationCategory: "UtilitiesApplication",
    operatingSystem: "Web Browser",
    url: SITE_URL,
    description: "100+ free PDF, Word, and image processing tools. Client-side, private, no upload required.",
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "USD",
    },
  };

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem('theme');if(t==='light'||t==='dark'){document.documentElement.setAttribute('data-theme',t)}else if(window.matchMedia&&window.matchMedia('(prefers-color-scheme:dark)').matches){document.documentElement.setAttribute('data-theme','dark')}}catch(e){}})()`,
          }}
        />
        <script {...jsonLdProps(organizationJsonLd)} />
        <script {...jsonLdProps(websiteJsonLd)} />
        <script {...jsonLdProps(softwareJsonLd)} />
        <link rel="dns-prefetch" href="https://www.google-analytics.com" />
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-RGZ4FLC926" />
        <script
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-RGZ4FLC926');`,
          }}
        />
        {/* Google Search Console verification — set GSC_VERIFICATION to the full `google-site-verification` meta content value */}
        {process.env.GSC_VERIFICATION && (
          <meta name="google-site-verification" content={process.env.GSC_VERIFICATION} />
        )}
        {/* Bing Webmaster Tools verification */}
        <meta name="msvalidate.01" content="00840B0DE02EF6E56ECFDB8FCA2620EB" />
        {/* Google AdSense — site ownership verification + ad serving (required in <head> on every page) */}
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5534909600353741"
          crossOrigin="anonymous"
        />
      </head>
      <body className="min-h-screen bg-bg-base text-text-primary antialiased">
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-50 focus:px-4 focus:py-2 focus:rounded-lg focus:bg-bg-surface focus:text-text-primary focus:ring-2 focus:ring-accent"
        >
          Skip to content
        </a>
        <ThemeProvider>
          <Header />
          <main className="min-h-[calc(100vh-3rem)]" id="main-content">{children}</main>
          <Footer />
          <FloatingActionButton />
          <CookieConsentBanner />
          <SupportBot />
        </ThemeProvider>
      </body>
    </html>
  );
}
