// components/tool-registry.tsx
// Maps tool slugs to lazy-loaded UI components.
// Each tool is code-split — only loads when the user opens that specific tool.

import dynamic from "next/dynamic";
import { ComponentType } from "react";

export interface ToolUIProps {
  onProcessing?: (processing: boolean) => void;
  onError?: (error: string) => void;
}

// Lazy-load tool UIs — Next.js will code-split each into its own chunk
const toolComponents: Record<string, ComponentType<ToolUIProps>> = {
  // Tier 1 PDF tools
  "merge-pdf": dynamic(() => import("./tools/merge-pdf"), { ssr: false }) as any,
  "split-pdf": dynamic(() => import("./tools/split-pdf"), { ssr: false }) as any,
  "rotate-pdf": dynamic(() => import("./tools/rotate-pdf"), { ssr: false }) as any,
  "delete-pdf-pages": dynamic(() => import("./tools/delete-pdf-pages"), { ssr: false }) as any,
  "extract-pdf-pages": dynamic(() => import("./tools/extract-pdf-pages"), { ssr: false }) as any,
  "reorder-pdf-pages": dynamic(() => import("./tools/reorder-pdf-pages"), { ssr: false }) as any,
  "organize-pdf": dynamic(() => import("./tools/organize-pdf"), { ssr: false }) as any,
  "insert-pdf-pages": dynamic(() => import("./tools/insert-pdf-pages"), { ssr: false }) as any,
  "add-blank-page-pdf": dynamic(() => import("./tools/add-blank-page-pdf"), { ssr: false }) as any,
  "watermark-pdf": dynamic(() => import("./tools/watermark-pdf"), { ssr: false }) as any,
  "add-page-numbers-pdf": dynamic(() => import("./tools/add-page-numbers-pdf"), { ssr: false }) as any,
  "protect-pdf": dynamic(() => import("./tools/protect-pdf"), { ssr: false }) as any,
  "unlock-pdf": dynamic(() => import("./tools/unlock-pdf"), { ssr: false }) as any,
  "jpg-to-pdf": dynamic(() => import("./tools/jpg-to-pdf"), { ssr: false }) as any,
  "png-to-pdf": dynamic(() => import("./tools/png-to-pdf"), { ssr: false }) as any,
  "images-to-pdf": dynamic(() => import("./tools/images-to-pdf"), { ssr: false }) as any,
  "edit-pdf-metadata": dynamic(() => import("./tools/edit-pdf-metadata"), { ssr: false }) as any,
  "pdf-info-viewer": dynamic(() => import("./tools/pdf-info-viewer"), { ssr: false }) as any,
  "text-to-pdf": dynamic(() => import("./tools/text-to-pdf"), { ssr: false }) as any,
  "pdf-to-text": dynamic(() => import("./tools/pdf-to-text"), { ssr: false }) as any,
  "crop-pdf": dynamic(() => import("./tools/crop-pdf"), { ssr: false }) as any,
  "resize-pdf-page": dynamic(() => import("./tools/resize-pdf-page"), { ssr: false }) as any,
  "pdf-to-grayscale": dynamic(() => import("./tools/pdf-to-grayscale"), { ssr: false }) as any,
  "edit-pdf": dynamic(() => import("./tools/edit-pdf"), { ssr: false }) as any,
  "sign-pdf": dynamic(() => import("./tools/sign-pdf"), { ssr: false }) as any,
  "pdf-header-footer": dynamic(() => import("./tools/pdf-header-footer"), { ssr: false }) as any,
  "pdf-stamp": dynamic(() => import("./tools/pdf-stamp"), { ssr: false }) as any,
  "redact-pdf": dynamic(() => import("./tools/redact-pdf"), { ssr: false }) as any,
  "compare-pdf": dynamic(() => import("./tools/compare-pdf"), { ssr: false }) as any,
  "pdf-to-jpg": dynamic(() => import("./tools/pdf-to-jpg"), { ssr: false }) as any,
  "compress-pdf": dynamic(() => import("./tools/compress-pdf"), { ssr: false }) as any,
  "pdf-to-png": dynamic(() => import("./tools/pdf-to-png"), { ssr: false }) as any,
  "html-to-pdf": dynamic(() => import("./tools/html-to-pdf"), { ssr: false }) as any,
  "markdown-to-pdf": dynamic(() => import("./tools/markdown-to-pdf"), { ssr: false }) as any,
  "pdf-to-html": dynamic(() => import("./tools/pdf-to-html"), { ssr: false }) as any,
  "pdf-to-csv": dynamic(() => import("./tools/pdf-to-csv"), { ssr: false }) as any,
  "flatten-pdf-form": dynamic(() => import("./tools/flatten-pdf-form"), { ssr: false }) as any,
  "pdf-bookmarks-editor": dynamic(() => import("./tools/pdf-bookmarks-editor"), { ssr: false }) as any,
  "pdf-to-epub": dynamic(() => import("./tools/pdf-to-epub"), { ssr: false }) as any,
  "pdf-to-markdown": dynamic(() => import("./tools/pdf-to-markdown"), { ssr: false }) as any,
  // New PDF tools
  "split-pdf-by-page-count": dynamic(() => import("./tools/split-pdf-by-page-count"), { ssr: false }) as any,
  "pdf-duplicate-pages": dynamic(() => import("./tools/pdf-duplicate-pages"), { ssr: false }) as any,
  "pdf-interleave": dynamic(() => import("./tools/pdf-interleave"), { ssr: false }) as any,
  "pdf-scale-pages": dynamic(() => import("./tools/pdf-scale-pages"), { ssr: false }) as any,
  "pdf-invert-colors": dynamic(() => import("./tools/pdf-invert-colors"), { ssr: false }) as any,
  "pdf-metadata-stripper": dynamic(() => import("./tools/pdf-metadata-stripper"), { ssr: false }) as any,
  "pdf-page-labels": dynamic(() => import("./tools/pdf-page-labels"), { ssr: false }) as any,
  "pdf-transparent-bg": dynamic(() => import("./tools/pdf-transparent-bg"), { ssr: false }) as any,
  "pdf-page-crop-marks": dynamic(() => import("./tools/pdf-page-crop-marks"), { ssr: false }) as any,
  "pdf-bates-numbering": dynamic(() => import("./tools/pdf-bates-numbering"), { ssr: false }) as any,
  "pdf-to-svg": dynamic(() => import("./tools/pdf-to-svg"), { ssr: false }) as any,
  "pdf-create-from-url": dynamic(() => import("./tools/pdf-create-from-url"), { ssr: false }) as any,
  "pdf-to-rtf": dynamic(() => import("./tools/pdf-to-rtf"), { ssr: false }) as any,
  "pdf-encrypt-check": dynamic(() => import("./tools/pdf-encrypt-check"), { ssr: false }) as any,
  "pdf-page-counter": dynamic(() => import("./tools/pdf-page-counter"), { ssr: false }) as any,
  "pdf-to-json": dynamic(() => import("./tools/pdf-to-json"), { ssr: false }) as any,
  "pdf-image-watermark": dynamic(() => import("./tools/pdf-image-watermark"), { ssr: false }) as any,
  "pdf-merge-single-page": dynamic(() => import("./tools/pdf-merge-single-page"), { ssr: false }) as any,
  "pdf-digital-stamp": dynamic(() => import("./tools/pdf-digital-stamp"), { ssr: false }) as any,
  "pdf-page-transition": dynamic(() => import("./tools/pdf-page-transition"), { ssr: false }) as any,
  // Form & OCR tools
  "fill-pdf-form": dynamic(() => import("./tools/fill-pdf-form"), { ssr: false }) as any,
  "create-pdf-form": dynamic(() => import("./tools/create-pdf-form"), { ssr: false }) as any,
  "ocr-pdf": dynamic(() => import("./tools/ocr-pdf"), { ssr: false }) as any,
  "scan-to-pdf": dynamic(() => import("./tools/scan-to-pdf"), { ssr: false }) as any,
  // Format conversion tools
  "pdf-to-word": dynamic(() => import("./tools/pdf-to-word"), { ssr: false }) as any,
  "pdf-to-powerpoint": dynamic(() => import("./tools/pdf-to-powerpoint"), { ssr: false }) as any,
  "pdf-to-excel": dynamic(() => import("./tools/pdf-to-excel"), { ssr: false }) as any,
  "word-to-pdf": dynamic(() => import("./tools/word-to-pdf"), { ssr: false }) as any,
  "powerpoint-to-pdf": dynamic(() => import("./tools/powerpoint-to-pdf"), { ssr: false }) as any,
  "excel-to-pdf": dynamic(() => import("./tools/excel-to-pdf"), { ssr: false }) as any,
  "pdf-to-word-2": dynamic(() => import("./tools/pdf-to-word-2"), { ssr: false }) as any,
  "word-to-pdf-2": dynamic(() => import("./tools/word-to-pdf-2"), { ssr: false }) as any,
  // Security & info tools
  "repair-pdf": dynamic(() => import("./tools/repair-pdf"), { ssr: false }) as any,
  "pdf-to-pdfa": dynamic(() => import("./tools/pdf-to-pdfa"), { ssr: false }) as any,
  "optimize-pdf-web": dynamic(() => import("./tools/optimize-pdf-web"), { ssr: false }) as any,
  "pdf-to-tiff": dynamic(() => import("./tools/pdf-to-tiff"), { ssr: false }) as any,
  "extract-images-from-pdf": dynamic(() => import("./tools/extract-images-from-pdf"), { ssr: false }) as any,
  "epub-to-pdf": dynamic(() => import("./tools/epub-to-pdf"), { ssr: false }) as any,
  "split-pdf-by-size": dynamic(() => import("./tools/split-pdf-by-size"), { ssr: false }) as any,
  "split-pdf-by-bookmarks": dynamic(() => import("./tools/split-pdf-by-bookmarks"), { ssr: false }) as any,
  "verify-pdf-signature": dynamic(() => import("./tools/verify-pdf-signature"), { ssr: false }) as any,
  "pdf-password-checker": dynamic(() => import("./tools/pdf-password-checker"), { ssr: false }) as any,
  // Batch & utility tools
  "batch-converter": dynamic(() => import("./tools/batch-converter"), { ssr: false }) as any,
  "side-by-side-diff": dynamic(() => import("./tools/side-by-side-diff"), { ssr: false }) as any,
  // Word tools
  "merge-word": dynamic(() => import("./tools/merge-word"), { ssr: false }) as any,
  "split-word": dynamic(() => import("./tools/split-word"), { ssr: false }) as any,
  "word-to-text": dynamic(() => import("./tools/word-to-text"), { ssr: false }) as any,
  "text-to-word": dynamic(() => import("./tools/text-to-word"), { ssr: false }) as any,
  "word-to-html": dynamic(() => import("./tools/word-to-html"), { ssr: false }) as any,
  "html-to-word": dynamic(() => import("./tools/html-to-word"), { ssr: false }) as any,
  "word-to-markdown": dynamic(() => import("./tools/word-to-markdown"), { ssr: false }) as any,
  "markdown-to-word": dynamic(() => import("./tools/markdown-to-word"), { ssr: false }) as any,
  "word-to-epub": dynamic(() => import("./tools/word-to-epub"), { ssr: false }) as any,
  "word-to-odt": dynamic(() => import("./tools/word-to-odt"), { ssr: false }) as any,
  "odt-to-word": dynamic(() => import("./tools/odt-to-word"), { ssr: false }) as any,
  "word-to-images": dynamic(() => import("./tools/word-to-images"), { ssr: false }) as any,
  "word-to-powerpoint": dynamic(() => import("./tools/word-to-powerpoint"), { ssr: false }) as any,
  "watermark-word": dynamic(() => import("./tools/watermark-word"), { ssr: false }) as any,
  "word-page-numbers": dynamic(() => import("./tools/word-page-numbers"), { ssr: false }) as any,
  "word-header-footer": dynamic(() => import("./tools/word-header-footer"), { ssr: false }) as any,
  "word-find-replace": dynamic(() => import("./tools/word-find-replace"), { ssr: false }) as any,
  "word-track-changes": dynamic(() => import("./tools/word-track-changes"), { ssr: false }) as any,
  "word-comments-extractor": dynamic(() => import("./tools/word-comments-extractor"), { ssr: false }) as any,
  "word-metadata-editor": dynamic(() => import("./tools/word-metadata-editor"), { ssr: false }) as any,
  "compare-word": dynamic(() => import("./tools/compare-word"), { ssr: false }) as any,
  "redact-word": dynamic(() => import("./tools/redact-word"), { ssr: false }) as any,
  "protect-word": dynamic(() => import("./tools/protect-word"), { ssr: false }) as any,
  "unlock-word": dynamic(() => import("./tools/unlock-word"), { ssr: false }) as any,
  "word-template-filler": dynamic(() => import("./tools/word-template-filler"), { ssr: false }) as any,
  "word-tables-to-excel": dynamic(() => import("./tools/word-tables-to-excel"), { ssr: false }) as any,
  "word-style-cleaner": dynamic(() => import("./tools/word-style-cleaner"), { ssr: false }) as any,
  "word-toc-generator": dynamic(() => import("./tools/word-toc-generator"), { ssr: false }) as any,
  "word-font-checker": dynamic(() => import("./tools/word-font-checker"), { ssr: false }) as any,
  "word-page-setup": dynamic(() => import("./tools/word-page-setup"), { ssr: false }) as any,
  // Image tools — Convert
  "jpg-to-png": dynamic(() => import("./tools/jpg-to-png"), { ssr: false }) as any,
  "png-to-jpg": dynamic(() => import("./tools/png-to-jpg"), { ssr: false }) as any,
  "webp-to-jpg": dynamic(() => import("./tools/webp-to-jpg"), { ssr: false }) as any,
  "jpg-to-webp": dynamic(() => import("./tools/jpg-to-webp"), { ssr: false }) as any,
  "png-to-webp": dynamic(() => import("./tools/png-to-webp"), { ssr: false }) as any,
  "webp-to-png": dynamic(() => import("./tools/webp-to-png"), { ssr: false }) as any,
  "heic-to-jpg": dynamic(() => import("./tools/heic-to-jpg"), { ssr: false }) as any,
  "heic-to-png": dynamic(() => import("./tools/heic-to-png"), { ssr: false }) as any,
  "tiff-to-jpg": dynamic(() => import("./tools/tiff-to-jpg"), { ssr: false }) as any,
  "bmp-to-jpg": dynamic(() => import("./tools/bmp-to-jpg"), { ssr: false }) as any,
  "gif-to-png": dynamic(() => import("./tools/gif-to-png"), { ssr: false }) as any,
  "gif-to-jpg": dynamic(() => import("./tools/gif-to-jpg"), { ssr: false }) as any,
  "svg-to-png": dynamic(() => import("./tools/svg-to-png"), { ssr: false }) as any,
  "svg-to-jpg": dynamic(() => import("./tools/svg-to-jpg"), { ssr: false }) as any,
  "png-to-svg": dynamic(() => import("./tools/png-to-svg"), { ssr: false }) as any,
  "ico-to-png": dynamic(() => import("./tools/ico-to-png"), { ssr: false }) as any,
  "png-to-ico": dynamic(() => import("./tools/png-to-ico"), { ssr: false }) as any,
  "avif-to-jpg": dynamic(() => import("./tools/avif-to-jpg"), { ssr: false }) as any,
  "raw-to-jpg": dynamic(() => import("./tools/raw-to-jpg"), { ssr: false }) as any,
  // Image tools — Crop & Resize
  "resize-image": dynamic(() => import("./tools/resize-image"), { ssr: false }) as any,
  "crop-image": dynamic(() => import("./tools/crop-image"), { ssr: false }) as any,
  "scale-image": dynamic(() => import("./tools/scale-image"), { ssr: false }) as any,
  "smart-crop": dynamic(() => import("./tools/smart-crop"), { ssr: false }) as any,
  // Image tools — Rotate & Flip
  "rotate-image": dynamic(() => import("./tools/rotate-image"), { ssr: false }) as any,
  "flip-image": dynamic(() => import("./tools/flip-image"), { ssr: false }) as any,
  "mirror-image": dynamic(() => import("./tools/mirror-image"), { ssr: false }) as any,
  "straighten-image": dynamic(() => import("./tools/straighten-image"), { ssr: false }) as any,
  // Image tools — Filters
  "blur-image": dynamic(() => import("./tools/blur-image"), { ssr: false }) as any,
  "sharpen-image": dynamic(() => import("./tools/sharpen-image"), { ssr: false }) as any,
  "grayscale-image": dynamic(() => import("./tools/grayscale-image"), { ssr: false }) as any,
  "sepia-image": dynamic(() => import("./tools/sepia-image"), { ssr: false }) as any,
  "invert-colors-image": dynamic(() => import("./tools/invert-colors-image"), { ssr: false }) as any,
  "threshold-image": dynamic(() => import("./tools/threshold-image"), { ssr: false }) as any,
  "emboss-image": dynamic(() => import("./tools/emboss-image"), { ssr: false }) as any,
  "edge-detect-image": dynamic(() => import("./tools/edge-detect-image"), { ssr: false }) as any,
  "oil-paint-image": dynamic(() => import("./tools/oil-paint-image"), { ssr: false }) as any,
  "cartoon-image": dynamic(() => import("./tools/cartoon-image"), { ssr: false }) as any,
  "sketch-image": dynamic(() => import("./tools/sketch-image"), { ssr: false }) as any,
  // Image tools — Adjust
  "brightness-contrast": dynamic(() => import("./tools/brightness-contrast"), { ssr: false }) as any,
  "saturation-adjust": dynamic(() => import("./tools/saturation-adjust"), { ssr: false }) as any,
  "hue-shift": dynamic(() => import("./tools/hue-shift"), { ssr: false }) as any,
  "exposure-adjust": dynamic(() => import("./tools/exposure-adjust"), { ssr: false }) as any,
  "color-temperature": dynamic(() => import("./tools/color-temperature"), { ssr: false }) as any,
  "vignette-image": dynamic(() => import("./tools/vignette-image"), { ssr: false }) as any,
  "gamma-adjust": dynamic(() => import("./tools/gamma-adjust"), { ssr: false }) as any,
  // Image tools — Effects
  "watermark-image": dynamic(() => import("./tools/watermark-image"), { ssr: false }) as any,
  "opacity-adjust": dynamic(() => import("./tools/opacity-adjust"), { ssr: false }) as any,
  "pixelate-image": dynamic(() => import("./tools/pixelate-image"), { ssr: false }) as any,
  "mosaic-image": dynamic(() => import("./tools/mosaic-image"), { ssr: false }) as any,
  "duotone-image": dynamic(() => import("./tools/duotone-image"), { ssr: false }) as any,
  "vintage-image": dynamic(() => import("./tools/vintage-image"), { ssr: false }) as any,
  "fade-image": dynamic(() => import("./tools/fade-image"), { ssr: false }) as any,
  "background-remove-image": dynamic(() => import("./tools/background-remove-image"), { ssr: false }) as any,
  "change-bg-color": dynamic(() => import("./tools/change-bg-color"), { ssr: false }) as any,
  // Image tools — Annotate
  "text-on-image": dynamic(() => import("./tools/text-on-image"), { ssr: false }) as any,
  "border-image": dynamic(() => import("./tools/border-image"), { ssr: false }) as any,
  "rounded-corners-image": dynamic(() => import("./tools/rounded-corners-image"), { ssr: false }) as any,
  "circle-crop-image": dynamic(() => import("./tools/circle-crop-image"), { ssr: false }) as any,
  "shadow-image": dynamic(() => import("./tools/shadow-image"), { ssr: false }) as any,
  "meme-generator": dynamic(() => import("./tools/meme-generator"), { ssr: false }) as any,
  "draw-on-image": dynamic(() => import("./tools/draw-on-image"), { ssr: false }) as any,
  "arrow-on-image": dynamic(() => import("./tools/arrow-on-image"), { ssr: false }) as any,
  "sticker-image": dynamic(() => import("./tools/sticker-image"), { ssr: false }) as any,
  // Image tools — Info
  "image-info": dynamic(() => import("./tools/image-info"), { ssr: false }) as any,
  "exif-viewer": dynamic(() => import("./tools/exif-viewer"), { ssr: false }) as any,
  "strip-metadata-image": dynamic(() => import("./tools/strip-metadata-image"), { ssr: false }) as any,
  "image-histogram": dynamic(() => import("./tools/image-histogram"), { ssr: false }) as any,
  "color-picker-image": dynamic(() => import("./tools/color-picker-image"), { ssr: false }) as any,
  "image-compare": dynamic(() => import("./tools/image-compare"), { ssr: false }) as any,
  // Image tools — Utility
  "compress-image": dynamic(() => import("./tools/compress-image"), { ssr: false }) as any,
  "image-to-pdf-image": dynamic(() => import("./tools/image-to-pdf-image"), { ssr: false }) as any,
  "svg-to-pdf-image": dynamic(() => import("./tools/svg-to-pdf-image"), { ssr: false }) as any,
  "image-to-base64": dynamic(() => import("./tools/image-to-base64"), { ssr: false }) as any,
  "base64-to-image": dynamic(() => import("./tools/base64-to-image"), { ssr: false }) as any,
  "image-qr-generator": dynamic(() => import("./tools/image-qr-generator"), { ssr: false }) as any,
  "barcode-generator": dynamic(() => import("./tools/barcode-generator"), { ssr: false }) as any,
  "favicon-generator": dynamic(() => import("./tools/favicon-generator"), { ssr: false }) as any,
  "image-collage": dynamic(() => import("./tools/image-collage"), { ssr: false }) as any,
  "images-to-grid": dynamic(() => import("./tools/images-to-grid"), { ssr: false }) as any,
  "photo-grid": dynamic(() => import("./tools/photo-grid"), { ssr: false }) as any,
  "image-strip": dynamic(() => import("./tools/image-strip"), { ssr: false }) as any,
  "before-after-slider": dynamic(() => import("./tools/before-after-slider"), { ssr: false }) as any,
  "image-tile": dynamic(() => import("./tools/image-tile"), { ssr: false }) as any,
  "color-palette": dynamic(() => import("./tools/color-palette"), { ssr: false }) as any,
  "placeholder-generator": dynamic(() => import("./tools/placeholder-generator"), { ssr: false }) as any,
  "gradient-generator": dynamic(() => import("./tools/gradient-generator"), { ssr: false }) as any,
  // Cross-format & utility tools
  "universal-converter": dynamic(() => import("./tools/universal-converter"), { ssr: false }) as any,
  "compress-word": dynamic(() => import("./tools/compress-word"), { ssr: false }) as any,
  "file-info": dynamic(() => import("./tools/file-info"), { ssr: false }) as any,
  "batch-rename-export": dynamic(() => import("./tools/batch-rename-export"), { ssr: false }) as any,
  "qr-to-pdf": dynamic(() => import("./tools/qr-to-pdf"), { ssr: false }) as any,
  "bulk-images-to-doc": dynamic(() => import("./tools/bulk-images-to-doc"), { ssr: false }) as any,
  "signature-manager": dynamic(() => import("./tools/signature-manager"), { ssr: false }) as any,
  "recent-tools": dynamic(() => import("./tools/recent-tools"), { ssr: false }) as any,
  "command-palette": dynamic(() => import("./tools/command-palette"), { ssr: false }) as any,
};

export function getToolComponent(slug: string) {
  return toolComponents[slug] || null;
}
